pipeline {
  agent any
  tools {nodejs "node"}
  stages {
    stage('Build') {
      steps {
        git 'https://github.com/GunnuD/simple-node-js-react-npm-app.git'
        bat 'npm install'
      }}}}
